# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ProjectHemeraAdmin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectHemeraAdmin
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'

  target 'ProjectHemeraAdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ProjectHemeraAdmin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectHemeraAdmin-tvOS

  target 'ProjectHemeraAdmin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
